([api.entity
  (z-orders
   max-delta-time
   render-order
   render-systems
   min-solid-body-size
   max-speed
   movement-speed-schema
   hpbar-height-px)]
 [app (state)]
 [context.properties (validate? write-to-file?)]
 [context.world (spawn-enemies? pausing? replay-speed)]
 [core.component
  (warn-on-override warn-name-ns-mismatch? attributes defsystems)]
 [core.data
  (val-max-attr
   sound
   animation
   nat-int-attr
   string-attr
   pos-attr
   boolean-attr
   pos-int-attr
   image)]
 [data.val-max (val-max-schema)]
 [entity-state.fsms
  (player-state-obj-constructors npc-state-obj-constructors)]
 [entity-state.npc-sleeping (aggro-range)]
 [entity.inventory (empty-inventory)]
 [entity.mouseover
  (neutral-color outline-alpha friendly-color enemy-color)]
 [entity.shout (shout-range)]
 [entity.stats
  (negative-modifier-color
   hpbar-colors
   borders-px
   stats-info-text-order
   positive-modifier-color)]
 [gdx.dev (obj app-ns refresh-error app-fn thrown nrepl-server)]
 [gdx.graphics.color
  (magenta
   purple
   scarlet
   brown
   sky
   olive
   black
   clear
   lime
   firebrick
   orange
   gray
   tan
   white
   light-gray
   yellow
   navy
   green
   cyan
   violet
   slate
   salmon
   dark-gray
   royal
   gold
   chartreuse
   forest
   red
   blue
   maroon
   coral
   goldenrod
   pink
   teal)]
 [gdx.input.buttons (middle left forward back right)]
 [gdx.input.keys
  (f19
   period
   f24
   print-screen
   t
   endcall
   x
   forward-del
   f9
   page-down
   end
   control-left
   left-bracket
   tab
   f15
   numpad-4
   f6
   max-keycode
   f4
   numpad-8
   numpad-right-paren
   numpad-subtract
   i
   numpad-dot
   p
   button-x
   button-a
   button-b
   a
   mute
   backslash
   num-2
   menu
   f13
   u
   shift-right
   any-key
   numpad-multiply
   clear
   left
   numpad-5
   num-9
   del
   media-previous
   escape
   dpad-up
   y
   numpad-add
   switch-charset
   num
   volume-up
   q
   envelope
   media-fast-forward
   r
   slash
   down
   pictsymbols
   headsethook
   insert
   v
   space
   home
   button-r2
   numpad-9
   control-right
   o
   f18
   num-8
   f21
   f8
   num-1
   alt-left
   button-l1
   button-start
   f10
   f1
   grave
   num-3
   shift-left
   meta-shift-right-on
   numpad-0
   call
   button-thumbl
   f16
   scroll-lock
   f20
   num-0
   notification
   f23
   unknown
   media-stop
   num-7
   meta-alt-right-on
   comma
   volume-down
   button-c
   numpad-divide
   alt-right
   n
   w
   explorer
   m
   page-up
   numpad-left-paren
   media-play-pause
   f5
   caps-lock
   numpad-comma
   minus
   button-z
   num-6
   numpad-equals
   star
   dpad-down
   soft-right
   search
   e
   num-5
   meta-shift-on
   s
   button-select
   equals
   k
   button-thumbr
   sym
   numpad-3
   colon
   num-lock
   media-next
   dpad-left
   l
   up
   numpad-1
   numpad-2
   right-bracket
   center
   enter
   numpad-6
   f11
   c
   power
   button-circle
   dpad-center
   z
   g
   f17
   button-r1
   numpad-enter
   numpad-7
   f3
   button-y
   meta-alt-left-on
   j
   back
   apostrophe
   soft-left
   button-l2
   h
   pound
   f2
   media-rewind
   plus
   semicolon
   at
   button-mode
   dpad-right
   b
   meta-shift-left-on
   f12
   f22
   meta-alt-on
   right
   f14
   focus
   meta-sym-on
   camera
   num-4
   pause
   backspace
   f7
   d
   f)]
 [mapgen.cave-gen (get-adj-num current-order turn-ratio)]
 [mapgen.module-gen
  (floor-modules-row-height
   uf-caves-scale
   transition-modules-row-width
   modules-file
   module-width
   floor-modules-row-width
   spawn-creatures?
   ground-sprites
   module-height
   uf-grounds
   scale
   number-modules-y
   number-modules-x
   uf-walls
   transition-modules-row-height
   sprite-size
   transition-modules-offset-x
   floor-idxvalue
   module-offset-tiles)]
 [mapgen.nad (diagonal-steps)]
 [mapgen.transitions (idxvalues)]
 [properties.skill
  (effect-color skill-cost-color action-time-color cooldown-color)]
 [screens.map-editor (zoom-speed camera-movement-speed infotext)]
 [screens.options-menu (key-help-text debug-flags)]
 [screens.world (zoom-speed)]
 [widgets.background-image (image-file)]
 [widgets.entity-info-window (info-text-key-order)]
 [widgets.inventory (droppable-color not-allowed-color cell-size)]
 [widgets.player-message (duration-seconds)]
 [world.debug-render
  (tile-grid?
   cell-occupied?
   highlight-blocked-cell?
   cell-entities?
   potential-field-colors?)]
 [world.ecs (this show-body-bounds)]
 [world.effect-handler (record-txs? debug-print-txs? frame->txs)]
 [world.line-of-sight (los-checks?)]
 [world.mouseover-entity (this-k)]
 [world.potential-fields
  (diagonal-check-indizes factions-iterations cache)]
 [world.render (see-all-tiles? explored-tile-color)])
