(ns gdl.input.keys
  (:refer-clojure :exclude [num]))

(declare a
         alt-left
         alt-right
         any-key
         apostrophe
         at
         b
         back
         backslash
         backspace
         button-a
         button-b
         button-c
         button-circle
         button-l1
         button-l2
         button-mode
         button-r1
         button-r2
         button-select
         button-start
         button-thumbl
         button-thumbr
         button-x
         button-y
         button-z
         c
         call
         camera
         caps-lock
         center
         clear
         colon
         comma
         control-left
         control-right
         d
         del
         down
         dpad-center
         dpad-down
         dpad-left
         dpad-right
         dpad-up
         e
         end
         endcall
         enter
         envelope
         equals
         escape
         explorer
         f
         f1
         f10
         f11
         f12
         f13
         f14
         f15
         f16
         f17
         f18
         f19
         f2
         f20
         f21
         f22
         f23
         f24
         f3
         f4
         f5
         f6
         f7
         f8
         f9
         focus
         forward-del
         g
         grave
         h
         headsethook
         home
         i
         insert
         j
         k
         l
         left
         left-bracket
         m
         max-keycode
         media-fast-forward
         media-next
         media-play-pause
         media-previous
         media-rewind
         media-stop
         menu
         meta-alt-left-on
         meta-alt-on
         meta-alt-right-on
         meta-shift-left-on
         meta-shift-on
         meta-shift-right-on
         meta-sym-on
         minus
         mute
         n
         notification
         num
         num-0
         num-1
         num-2
         num-3
         num-4
         num-5
         num-6
         num-7
         num-8
         num-9
         num-lock
         numpad-0
         numpad-1
         numpad-2
         numpad-3
         numpad-4
         numpad-5
         numpad-6
         numpad-7
         numpad-8
         numpad-9
         numpad-add
         numpad-comma
         numpad-divide
         numpad-dot
         numpad-enter
         numpad-equals
         numpad-left-paren
         numpad-multiply
         numpad-right-paren
         numpad-subtract
         o
         p
         page-down
         page-up
         pause
         period
         pictsymbols
         plus
         pound
         power
         print-screen
         q
         r
         right
         right-bracket
         s
         scroll-lock
         search
         semicolon
         shift-left
         shift-right
         slash
         soft-left
         soft-right
         space
         star
         switch-charset
         sym
         t
         tab
         u
         unknown
         up
         v
         volume-down
         volume-up
         w
         x
         y
         z)
